project:
  type: website
  output-dir: "docs"

website:
  title: "EACSII-2023"
  site-url: https://fcpys.github.io/eacsii2023/
  repo-url: https://github.com/fcpys/eacsii2023/
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: equipo.qmd
        text: Equipo docente
      - href: about.qmd
        text: Programa 
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Instalar R"
        contents:
          - instala.qmd
      - section: "Talleres"
        contents:
          - P1.qmd
          - P2.qmd
          - P3.qmd
format:
  html:
    theme: 
      light: pulse
      dark: darkly
    css: styles.css
    toc: true

editor: visual

